apiVersion: v1
kind: Service
metadata:
  name: log-bank-service
spec:
  selector:
    app: log-bank
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-bank-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-bank
  template:
    metadata:
      labels:
        app: log-bank
    spec:
      containers:
        - name: log-bank
          image: zeusmarval/log-bank:latest
          ports:
            - containerPort: 8080